### ISSUE TITLE
Access violation when TMPVPlayer.Close used in rmOpenGL mode

### ISSUE THREAD

**Issue by zbyna** [URUWorks/UW_MPVPlayer#1]
Hello,
when **TMPVPlayer.Close** used in **rmOpenGL** mode it throws Access violation error. In **rmEmbedding** no error.

The error is thrown on line **883**:

```pascal
procedure TMPVPlayer.UnInitialize;
...
 if Assigned(mpv_terminate_destroy) and Assigned(FMPV_HANDLE) then
    mpv_terminate_destroy(FMPV_HANDLE^);  
...
``` 
What is the purpose of  **TMPVPlayer.Close** ? 
I would need to clear the player screen after stopping video to show my own image - i.e. override **procedure EraseBackground(DC: HDC)** from parents and **TMPVPlayer.Close** seems like a promise choice.

Thanks for any hint

My specs:
 ```Lazarus 2.3.0 (rev main-2_3-2346-g0a34290)
 FPC 3.3.1 x86_64-win64-win32/win64
Microsoft Windows 10 Pro 10.0.19045
x64-based PC Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
```

**Comment by URUWorks** [comment]
I cannot reproduce the fault on my system.
Does it always happen in OpenGL mode with a special file?
Can you attach a test project?

TMPVPlayer.Close, uninitializes the libmpv library.

**Comment by zbyna** [comment]
This file always throws the error:
```
    reading file
    File loaded
    Video Width: 1280
    Video Height: 720
    Video Total Frames: 112926
    Video FPS: 30
    Buffering: 100%
    (cplayer) info:  (+) Video --vid=1 (*) (h264 1280x720 30.000fps)
    (cplayer) info:  (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
    (cplayer) info: AO: [wasapi] 48000Hz stereo 2ch float
    (cplayer) info: VO: [gpu] 1280x720 yuv420p
``` 
This file sometimes (one from five attempts) throws the error:
```
reading file
File loaded
Video Width: 270
Video Height: 270
Video Total Frames: 31758
Video FPS: 1
Buffering: 100%
(ffmpeg/demuxer) warn: mp3: Estimating duration from bitrate, this may be inaccurate
(cplayer) info:  (+) Video --vid=1 [P] (png 270x270 1.000fps)
(cplayer) info:  (+) Audio --aid=1 (mp3 2ch 44100Hz)
(display-tags) info: File tags:
(cplayer) info: Displaying cover art. Use --no-audio-display to prevent this.
``` 

This file never throws the error:
```
    reading file
    File loaded
    Video Width: 500
    Video Height: 500
    Video Total Frames: 64065
    Video FPS: 1
    Buffering: 100%  
    (ffmpeg/demuxer) warn: mov,mp4,m4a,3gp,3g2,mj2: stream 0, timescale not set
    (cplayer) info:  (+) Video --vid=1 [P] (mjpeg 1.000fps)
    (cplayer) info:  (+) Audio --aid=1 (*) (aac 2ch 22050Hz)
    (display-tags) info: File tags:
    (cplayer) info: Displaying cover art. Use --no-audio-display to prevent this.
    (cplayer) info: VO: [gpu] 500x500 yuv420p
     (cplayer) info: AO: [wasapi] 48000Hz stereo 2ch float
``` 

Testing project is the demo from this repository with this change:

![image](https://github.com/URUWorks/UW_MPVPlayer/assets/3373705/45e8d849-b66c-4def-8352-61b8b44fb2ae)
project attached:
[project1.zip](https://github.com/URUWorks/UW_MPVPlayer/files/13939875/project1.zip)

video from testing: https://youtu.be/o_Jtsuc9PNI

**Comment by URUWorks** [comment]
I still don't reproduce the problem... 
when you change the order of the mpv_terminate_destroy line, does it solve it?

With mpv.close does the app close? should not.

**Comment by zbyna** [comment]
When I changed the order of mpv_terminate_destroy line, the exact place where is shown in video mentioned in the post above, demo application was closed. 

In my opinion the error may arise from the fact that mpv_terminate_destroy is not called from the right thread or it tries to use something which was destroyed sooner?

**Comment by URUWorks** [comment]
I don't think mpv_terminated_destroy is the problem because it only fails in opengl mode.

Also I don't know if it improves anything, but I made some changes so that gl swapbuffer does not occur if the control is being destroyed...

you can try :)

**Comment by zbyna** [comment]
Still the same issue 🙁 
I have attached a small - about 1 minute extracted sample of the 1-hour file, which always caused error. 
This sample fails 2 times from 3 attempts.

![image](https://github.com/URUWorks/UW_MPVPlayer/assets/3373705/68b60a89-a755-48ff-b7b6-29c88b6de52e)
![image](https://github.com/URUWorks/UW_MPVPlayer/assets/3373705/de62b8cd-e9de-41b6-8cbd-1f7a27bf5f63)
![image](https://github.com/URUWorks/UW_MPVPlayer/assets/3373705/7aa9dfe1-616f-468a-b4b9-3acad7834e60)

https://github.com/URUWorks/UW_MPVPlayer/assets/3373705/94db0ad4-e538-45e0-be29-8c3b69816893

**Comment by URUWorks** [comment]
So the problem is when uninitializing GL, It is no longer the same error as at the beginning of the report.

Some doubts, 
- Are you using updated libmpv?
- Does the problem only happen when the video is playing?

Also I tried with the video you uploaded, and works perfectly for me :D

**Comment by zbyna** [comment]
The testing is still the same. In above attached project clicked the button which triggers mov.close . Then video is unloaded and error is thrown. As you can see in video above attached.

I am using libmpv bundled with  this project.

I am sure that you have faster system 🙂 That may be the reason for not encountering the error. Uninitialising GL take more time on my system and others part of program do not wait for it or something is uninitialised more times and the second attempt fails or something different 🙂

**Comment by URUWorks** [comment]
I was referring to the crash of the first post, is marked on another line :)

do you have discord? there we can continue more fluidly

**Comment by zbyna** [comment]
No I have not Discord.  As for direct communication, I am getting recovered slowly from meningitis which hit me in April.  I have problems with speaking due to paresis of the facial nerve as result of this illness.  I am not able to speak for long time, sorry.  
We can leave this issue open, I will use embedded mode for my application and  will  slowly continue to change mplayer engine to mpv engine in it.

**Comment by URUWorks** [comment]
Thank you, we hope this problem can be solved.

The best for you.

**Comment by zbyna** [comment]
I added PR which solves my issue  🙂 .

**Comment by URUWorks** [comment]
Great, can we close the issue ?

**Comment by zbyna** [comment]
Thanks for merge!
I think yes. I hope my testing was sufficient and this issue will remain closed 🙂
